server:
  port: 8081
  servlet:
    context-path: /

grpc:
  server:
    port: 9091

spring:
  application:
    name: file-storing-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/storing_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method

file:
  storage:
    path: ${FILE_STORAGE_PATH:/app/files}
    max-file-size: 50MB
    allowed-extensions: jpg,jpeg,png,pdf,doc,docx,xls,xlsx,txt

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.example.file.storing: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.example.file.storing: DEBUG
    org.springframework: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod